[package]
name = "probe"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
colored = "3.0.0"
grep = "0.3.2"
ignore = "0.4"
tree-sitter = "0.24.5"
tree-sitter-rust = "0.23.2"
tree-sitter-javascript = "0.23.1"
tree-sitter-typescript = "0.23.2"
tree-sitter-python = "0.23.6"
tree-sitter-go = "0.23.4"
tree-sitter-c = "0.23.4"
tree-sitter-cpp = "0.23.4"
tree-sitter-java = "0.23.5"
tree-sitter-ruby = "0.23.1"
tree-sitter-php = "0.23.11"
tree-sitter-swift = { version = "0.7.0" }
tree-sitter-c-sharp = { version = "0.23.1" }
ast-grep-core = "0.36.1"
ast-grep-language = "0.36.1"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-stemmers = "1.2"
tokio = { version = "1", features = ["full"] }
tiktoken-rs = "0.6.0"
regex = "1.9"
futures = "0.3"
itertools = "0.14.0"
rayon = "1.8"
once_cell = "1.19.0"
decompound = "0.3.0"
thiserror = "2.0.12"
tracing-subscriber = "0.3"
rig-core = "0.9.1"
lazy_static = "1.4.0"

[dev-dependencies]
tempfile = "3.7"
proptest = "1.2"
criterion = "0.5"

[lib]
name = "probe"
path = "src/lib.rs"

[[bin]]
name = "probe"
path = "src/main.rs"
