# .github/workflows/deploy.yml
name: Build and Deploy VitePress Site

on:
  push:
    branches: ["main"] # Trigger on push to main branch
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for lastUpdated (optional)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # Cache npm dependencies
          cache-dependency-path: site/package-lock.json # Specify the path to package-lock.json

      - name: Install Dependencies
        run: cd site && npm ci # Use npm ci for a clean install in the site directory

      - name: Build VitePress Site
        run: cd site && npm run docs:build # Build the VitePress site in the site directory

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/.vitepress/dist # Upload the VitePress build output as the artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
