# .github/workflows/deploy.yml
name: Build and Deploy VitePress Site

on:
  push:
    branches: ['main'] # Trigger on push to main branch
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for lastUpdated (optional)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Cache npm dependencies

      - name: Install Dependencies
        run: npm ci # Use npm ci for a clean install

      - name: Build VitePress Site
        run: npm run docs:build # Assumes 'docs:build' is set to 'vitepress build docs'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site # Upload the 'site' folder as the artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
